REM INSERTING into FPT.DVNB_DRIVER
SET DEFINE OFF;
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M01','Theo số lượng thẻ.','Debit hoặc Credit','KHCN hoặc KHDN','Đơn vị kinh doanh','MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M02','Theo doanh số giao dịch.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M03','Theo doanh số giao dịch MoneySend/ FundTranfer.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M04','Theo doanh số giao dịch quốc tế.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M06','Số lượt giao dịch thẻ Debit Doanh nghiệp.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M07','Theo doanh số giao dịch thẻ Debit.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M08','Theo doanh số giao dịch Credit doanh nghiệp trong nước.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M09','Số lượt giao dịch thẻ.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M10','Số lượt giao dịch thẻ MoneySend/FundTranfer.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M11','Số lượt giao dịch thẻ mua hàng hóa qua mạng.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M12','Số lượt giao dịch thẻ nước ngoài.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M13','Số lượt giao dịch thẻ trong nước.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M14','Số lượt giao dịch thẻ Debit.',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('M15','Theo doanh số giao dịch Credit trong nước',null,null,null,'MC');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V01','Số lượng thẻ.','Debit hoặc Credit','KHCN hoặc KHDN','Đơn vị kinh doanh','VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V02','Số lượng thẻ Visa Gold.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V03','Số lượng thẻ Visa Platinum.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V04','Doanh số giao dịch.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V05','Doanh số giao dịch thẻ trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V06','Doanh số giao dịch thẻ nước ngoài.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V07','Doanh số giao dịch thẻ Credit trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V08','Doanh số giao dịch thẻ Credit nước ngoài.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V09','Doanh số giao dịch thẻ Debit trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V10','Doanh số giao dịch thẻ Debit nước ngoài.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V11','Số lượng giao dịch.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V12','Số lượng giao dịch trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V13','Số lượng giao dịch nước ngoài.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V14','Số lượng giao dịch mua hàng hóa qua mạng.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V15','Số lượng giao dịch Credit nước ngoài.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V16','Số lượng giao dịch Credit trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V17','Số lượng giao dịch Debit trong nước.',null,null,null,'VS');
Insert into FPT.DVNB_DRIVER (DRIVER_CDE,DESCRIPTION,CARD_TYPE,CUSTOMER,BRANCH,CRD_BRN) values ('V18','Số lượng giao dịch Debit nước ngoài.',null,null,null,'VS');
commit;
