REM INSERTING into FPT.DVNB_DESCRIPTION
SET DEFINE OFF;
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1413','Quản lý các công cụ trên hệ thống của TCTQT','DVNB',46);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1414','Giám sát tuân thủ','DVNB',47);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1415','Thực hiện các công việc đảm bảo tuân thủ','DVNB',48);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1416','Theo dõi các khoản phí/hoàn trả liên quan tuân thủ và CT bồi hoàn rủi ro','DVNB',49);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1417','Truyền thông rủi ro giao dịch thẻ và NHĐT','DVNB',50);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1449','Ký quỹ đảm bảo duy trì giao dịch với TCTQT','DVNB',51);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1445','Báo cáo QLRRVH (báo cáo tháng nội bộ SCB)','DVNB',55);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1446','Báo cáo theo yêu cầu từ NHNN và cơ quan thẩm quyền','DVNB',56);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1440','Phân bổ thu nhập, chi phí IBT','DVNB',31);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1441','Phân bổ thu nhập, chi phí billing, topup','DVNB',32);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1442','Phân bổ thu nhập, chi phí ecommerce','DVNB',33);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1443','Phân bổ thu nhập, chi phí  Ví điện tử','DVNB',34);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1444','Phân bổ chi phí Mobile Banking','DVNB',35);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1434','Phân bổ thu nhập, chi phí POS','DVNB',36);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1435','Phân bổ thu nhập, chi phí thẻ tín dụng quốc tế','DVNB',37);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1436','Phân bổ thu nhập, chi phí thẻ thanh toán quốc tế','DVNB',38);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1437','Phân bổ thu nhập, chi phí thẻ nội địa','DVNB',39);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1438','Phân bổ thu nhập, chi phí thẻ quốc tế của Ngân hàng khác giao dịch tại ATM SCB','DVNB',40);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1439','Phân bổ thu nhập, chi phí thẻ nội địa của Ngân hàng khác giao dịch tại ATM SCB','DVNB',41);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1410','Rà soát cảnh báo rủi ro giao dịch thẻ','DVNB',42);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1412','Cập nhật tiêu chí cảnh báo giao dịch thẻ, NHĐT, POS SCB','DVNB',44);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1402','Báo cáo sự cố và tạm ứng hoàn trả tiền cho KH trong giao dịch thẻ và NHĐT','DVNB',45);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1447','Báo cáo ATM theo yêu cầu của TCTQT','DVNB',57);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1448','Báo cáo quý theo yêu cầu của TCTQT','DVNB',59);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201904','04/2019','KYSAOKE',3);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201905','05/2019','KYSAOKE',4);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201906','06/2019','KYSAOKE',5);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201907','07/2019','KYSAOKE',6);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201908','08/2019','KYSAOKE',7);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201909','09/2019','KYSAOKE',8);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201910','10/2019','KYSAOKE',9);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201911','11/2019','KYSAOKE',10);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201912','12/2019','KYSAOKE',11);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('012020','01/2020','KYSAOKE',12);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('022020','02/2020','KYSAOKE',13);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201901','01/2019','KYSAOKE',0);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201902','02/2019','KYSAOKE',1);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201903','03/2019','KYSAOKE',2);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1403','Tra soát thẻ quốc tế SCB với lý do giao dịch gian lận','DVNB',0);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1405','Tra soát thẻ nội địa SCB','DVNB',1);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1406','Tra soát thẻ Ngân hàng khác tại ATM SCB','DVNB',2);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1407','Tra soát thẻ Ngân hàng khác tại POS SCB','DVNB',3);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1408','Tra soát giao dịch NHĐT chiều phát hành','DVNB',4);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1409','Tra soát giao dịch NHĐT chiều thụ hưởng','DVNB',5);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1400','Giám sát giao dịch tại ĐVCNT SCB','DVNB',13);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1401','Rà soát cảnh báo rủi ro giao dịch tại ĐVCNT SCB','DVNB',14);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1418','Đối soát giao dịch thẻ tín dụng quốc tế','DVNB',15);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1419','Đối soát giao dịch thẻ thanh toán quốc tế','DVNB',16);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1421','Đối soát giao dịch thẻ nội địa','DVNB',17);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1423','Đối soát giao dịch tại POS SCB','DVNB',18);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420','Đối soát giao dịch thẻ quốc tế của Ngân hàng khác tại ATM SCB','DVNB',19);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1422','Đối soát giao dịch thẻ nội địa của Ngân hàng khác tại ATM SCB','DVNB',20);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1424','Đối soát ngày giao dịch billing, topup','DVNB',21);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1425','Đối soát ngày giao dịch ecommerce','DVNB',22);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1426','Đối soát ngày giao dịch chuyển tiền nhanh 24/7 chiều phát hành','DVNB',23);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1427','Đối soát ngày giao dịch chuyển tiền nhanh 24/7 chiều thụ hưởng','DVNB',24);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1428','Đối soát tháng giao dịch chuyển tiền nhanh 24/7','DVNB',25);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1429','Đối soát tháng giao dịch billing, topup','DVNB',26);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1430','Đối soát tháng giao dịch ecommerce','DVNB',27);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1431','Đối soát tháng giao dịch Ví điện tử','DVNB',28);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1432','Đối soát tháng phí dịch vụ Mobile Banking','DVNB',29);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1433','Đối soát tháng phí dịch vụ SMS','DVNB',30);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202001','01/2020','KYBAOCAO',12);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202002','02/2020','KYBAOCAO',13);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202003','03/2020','KYBAOCAO',14);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202004','04/2020','KYBAOCAO',15);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202005','05/2020','KYBAOCAO',16);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202006','06/2020','KYBAOCAO',17);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201901','01/2019','KYBAOCAO',0);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201902','02/2019','KYBAOCAO',1);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201903','03/2019','KYBAOCAO',2);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201904','04/2019','KYBAOCAO',3);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201905','05/2019','KYBAOCAO',4);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201906','06/2019','KYBAOCAO',5);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201907','07/2019','KYBAOCAO',6);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201908','08/2019','KYBAOCAO',7);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201909','09/2019','KYBAOCAO',8);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201910','10/2019','KYBAOCAO',9);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201911','11/2019','KYBAOCAO',10);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('201912','12/2019','KYBAOCAO',11);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202007','07/2020','KYBAOCAO',18);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202008','08/2020','KYBAOCAO',19);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202009','09/2020','KYBAOCAO',20);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202101','01/2021','KYBAOCAO',24);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202102','02/2021','KYBAOCAO',25);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202103','03/2021','KYBAOCAO',26);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202104','04/2021','KYBAOCAO',27);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202105','05/2021','KYBAOCAO',28);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202106','06/2021','KYBAOCAO',29);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202107','07/2021','KYBAOCAO',30);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202108','08/2021','KYBAOCAO',31);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202109','09/2021','KYBAOCAO',32);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202110','10/2021','KYBAOCAO',33);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202111','11/2021','KYBAOCAO',34);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202112','12/2021','KYBAOCAO',35);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420101','Nghiên cứu, khảo sát, phân tích và đánh giá các sản phẩm, dịch vụ, ứng dụng Thẻ, Ngân Hàng Số, đối tác liên kết... hiện có trên thị trường của các NH và tổ chức tín dụng khác từ đó đề xuất góp ý các sản phẩm và tính năng phù hợp cho SCB','DVNB',200);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420201','Các dự án về xây dựng/phát triển sản phẩm/tính năng mới cũng như các yêu cầu về cải tiến, tinh chỉnh sản phẩm/ứng dụng liên quan đến Thẻ và NHS phục vụ cho Khối Doanh Nghiệp (bao gồm thời gian hỗ trợ, tinh chỉnh sau khi dự án được triển khai)','DVNB',201);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420202','Các dự án về xây dựng/phát triển sản phẩm/tính năng mới liên quan đến Thẻ và NHS phục vụ cho Khối DVNH&TCCN (bao gồm thời gian hỗ trợ, tinh chỉnh sau khi dự án được triển khai)','DVNB',202);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420203','Thực hiện cải tiến, tinh chỉnh sản phẩm/ứng dụng liên quan đến Thẻ và NHS phục vụ cho Khối DN (bao gồm thời gian hỗ trợ, tinh chỉnh sau được triển khai)','DVNB',203);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1420204','Thực hiện cải tiến, tinh chỉnh sản phẩm/ứng dụng liên quan đến Thẻ và NHS phục vụ cho Khối DVNH&TCCN (bao gồm thời gian hỗ trợ, tinh chỉnh sau được triển khai)','DVNB',204);
commit;
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1430101','Tìm kiếm và làm việc với đối tác liên kết (bao gồm tìm kiếm, thực hiện thương thảo ký kết hợp đồng, triển khai kết nối..) để mở rộng và hợp tác dịch vụ tài chính, ngân hàng trên nền tảng số','DVNB',205);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1440101','Phối hợp với các Phòng trong nội bộ Khối Thẻ & NHS xây dựng & cải tiến các quy định/quy trình chính sách liên quan đến hoạt động Thẻ/NHS -  Bao gồm họp, góp ý, phối hợp cung cấp thông tin, xây dựng chính sách','DVNB',206);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1450101','Tham gia họp, tham dự hội thảo/ workshop do TCTQT/TB QLRR tổ chức','DVNB',207);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1450102','Thực hiện góp ý Tài liệu chất lượng / Hợp đồng hợp tác với các đối tác','DVNB',208);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1450103','Phản hồi ý kiến / Thực hiện các công việc theo PYC','DVNB',209);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1450201','Báo cáo theo yêu cầu từ Ngân hàng Nhà nước, cơ quan thẩm quyền (Báo cáo định kỳ hàng tháng và báo cáo khi có yêu cầu)','DVNB',210);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1411','Báo cáo và xử lý tổn thất trong giao dịch thẻ và NHĐT','DVNB',45);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1404','Tra soát thẻ quốc tế SCB với các lý do khác','DVNB',0);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_1450','Quản lý hạn mức Bù trừ điện tử (BTĐT)','DVNB',51);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3370101','Thực hiện các dự án liên quan Thẻ và Ngân hàng số phục vụ kinh doanh K.DVNH&TCCN','DVNB',100);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3370102','Thực hiện các dự án liên quan Thẻ và Ngân hàng số phục vụ kinh doanh K.DN','DVNB',101);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3370103','Thực hiện tinh chỉnh hệ thống liên quan Thẻ và Ngân hàng số phục vụ kinh doanh K.DVNH&TCCN','DVNB',102);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3370104','Thực hiện tinh chỉnh hệ thống liên quan Thẻ và Ngân hàng số phục vụ kinh doanh K.DN','DVNB',103);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3380101','Xử lý lỗi và sự cố liên quan đến hệ thống vận hành thẻ, hệ thống chuyển mạch và hệ thống ngân hàng số. - Cập nhật các bản nâng cấp/bản vá lỗi','DVNB',104);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3380201','Cung cấp dữ liệu cho các ứng dụng khác và theo yêu cầu của các Phòng/Đơn vị.','DVNB',105);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3380301','Quản lý và phân quyền tài khoản người dùng trên hệ thống thẻ và ngân hàng số','DVNB',106);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3380401','Cài đặt & quản lý mã khóa ATM','DVNB',107);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3380501','Xử lý cuối ngày hệ thống thẻ','DVNB',108);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390101','Quản lý và cài đặt, cập nhật tham số sản phẩm/dịch vụ thẻ và ngân hàng số','DVNB',109);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390201','Nhập liệu và phê duyệt hồ sơ phát hành/nâng/giảm... hạn mức thẻ (đã được cấp thẩm quyền phê duyệt) trên hệ thống theo quy định','DVNB',110);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390301','Mua sắm ATM, hóa đơn ATM, các thiết bị của ATM','DVNB',111);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390302','Mua sắm POS, hóa đơn POS','DVNB',112);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390303','Mua sắm phôi thẻ, các ấn phẩm phục vụ công tác phát hành thẻ','DVNB',113);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390401','Hỗ trợ phát hành thẻ nội địa (dập thẻ, phân phối thẻ, hỗ trợ Đơn vị trong công tác phát hành thẻ).','DVNB',114);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390402','Hỗ trợ nghiệp vụ thẻ quốc tế (gửi file cá thể hóa thẻ, theo dõi giao nhận thẻ..).','DVNB',115);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390403','Hỗ trợ mở và sử dụng dịch vụ ngân hàng điện tử, phân phối thiết bị xác thực (token).','DVNB',116);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202010','10/2020','KYBAOCAO',21);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202011','11/2020','KYBAOCAO',22);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('202012','12/2020','KYBAOCAO',23);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390501','Theo dõi cân đối thẻ TDQT, Theo dõi các tài khoản trung gian của thẻ, Chấm số liệu hạch toán vào ERP, Xử lý các khoản lệch phát sinh (nếu có)','DVNB',117);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390502','Giám sát và xử lý các vấn đề liên quan đến nghiệp vụ thẻ tín dụng (sao kê, điểm thưởng, thanh toán dư nợ thẻ tín dụng, SMS, trả góp thẻ tín dụng, hóa đơn, tính lãi, hoàn dư có/phí/lãi…)','DVNB',118);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390601','Giám sát và xử lý các vấn đề liên quan đến nghiệp vụ Ngân hàng Số (thu phí dịch vụ: MB, IB, gửi tin nhắn SMS theo yêu cầu…)','DVNB',119);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390701','Phân bổ chi phí phôi thẻ','DVNB',120);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390801','Đối soát với các đối tác và phân bổ chi phí liên quan giao dịch trả góp','DVNB',121);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3390901','Phối hợp lắp đặt/thay thế/di dời/chấm dứt hoạt động ATM/POS','DVNB',122);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3391001','Hỗ trợ ĐVKD cài đặt ứng dụng/thông số ATM/POS/thiết bị xác thực','DVNB',123);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400101','Báo cáo TT11 (báo cáo tháng nội bộ SCB)','DVNB',124);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400102','Báo cáo theo yêu cầu từ Ngân hàng Nhà nước, cơ quan thẩm quyền (Báo cáo định kỳ hàng tháng/quý/năm và báo cáo khi có yêu cầu)','DVNB',125);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400201','Tham gia họp, tham dự hội thảo/ workshop do TCTQT/Đối tác cung cấp giải pháp... tổ chức','DVNB',126);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400202','Thực hiện góp ý Tài liệu chất lượng / Hợp đồng hợp tác với các đối tác','DVNB',127);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400203','Phản hồi ý kiến / Thực hiện các công việc theo PYC','DVNB',128);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400204','Tu chỉnh/soạn thảo tài liệu chất lượng','DVNB',129);
Insert into FPT.DVNB_DESCRIPTION (ID,DESCRIPTION,TYPE,SEQUENCENO) values ('ACT_3400205','Ban hành các thông báo, hướng dẫn nghiệp vụ','DVNB',130);
commit;
